### ISSUE TITLE
HTML Publisher not configuring

### ISSUE THREAD

**Issue by robpark** [constantcontact/jenkins_pipeline_builder#75]
This new publisher broke my extension for the same and hasn't made it to the wiki for how to configure it. From looking at the source, it looks like I need a "report_targets" node of some sort?

Tried this, but it didn't work:

````
        - html_publisher:
            report_targets:
                report_title: 'Features'
                report_dir: 'out/cucumber'
                index_pages: 'features.html'
````

Thanks.

**Comment by crimsonknave** [comment]
It looks like report_targets is a hash in the yaml you have. It needs to be an array of hashes.

**Comment by robpark** [comment]
?

````
        - html_publisher:
            - report_title: 'Features'
              report_dir: 'out/cucumber'
              index_pages: 'features.html'
````

````
/Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions/helpers/extension_helper.rb:19:in `method_missing': no implicit conversion of Symbol into Integer (TypeError)
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions/publishers.rb:473:in `block (4 levels) in <top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:391:in `call'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions/publishers.rb:472:in `block (3 levels) in <top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:391:in `call'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:391:in `insert'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:375:in `method_missing'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions/publishers.rb:471:in `block (2 levels) in <top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions.rb:71:in `instance_exec'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions.rb:71:in `block in execute'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:293:in `initialize'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:254:in `new'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/builder.rb:254:in `with'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/extensions.rb:68:in `execute'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:100:in `block in traverse_registry'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:90:in `each'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:90:in `traverse_registry'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:106:in `block (2 levels) in traverse_registry'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:105:in `each'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:105:in `block in traverse_registry'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:90:in `each'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:90:in `traverse_registry'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/module_registry.rb:86:in `traverse_registry_path'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/job.rb:127:in `setup_freestyle_base'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/job.rb:38:in `to_xml'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/job.rb:18:in `create_or_update'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:217:in `block in publish_jobs'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:212:in `each'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:212:in `publish_jobs'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:201:in `block in publish_project'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:191:in `each'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:191:in `publish_project'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/generator.rb:54:in `bootstrap'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/lib/jenkins_pipeline_builder/cli/pipeline.rb:36:in `bootstrap'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/rob/.rvm/gems/ruby-2.2.1/gems/jenkins_pipeline_builder-0.11.0/bin/generate:25:in `<top (required)>'
	from /Users/rob/.rvm/gems/ruby-2.2.1/bin/generate:23:in `load'
	from /Users/rob/.rvm/gems/ruby-2.2.1/bin/generate:23:in `<main>'
	from /Users/rob/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/rob/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
````

**Comment by crimsonknave** [comment]
Sorry, I meant that the contents of report_targets should be an array of hashes.

```
- html_publisher:
    report_targets:
      - report_title: 'Features'
        report_dir: 'out/cucumber'
        index_pages: 'features.html'
```

**Comment by robpark** [comment]
That makes sense.
And it works :)
Thanks.
